name: Download

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 60
  download-latest:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: Download
        uses: ./
        with:
          latest: true
          path: artifact

      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA

  download-name:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: Download
        uses: ./
        with:
          name: artifact1
          path: artifact

      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA

  download-multiple:
    runs-on: ubuntu-latest
    needs: wait
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: Download
        uses: ./

      - name: Test
        run: |
          cat artifact1/sha1 | grep $GITHUB_SHA
          cat artifact2/sha2 | grep $GITHUB_SHA
